[package]
name = "vsg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.4", features = [ "derive" ] }
env_logger = "0.9"
winit = "0.26"
pollster = "0.2"
log = "0.4"
image = "0.24"
wgpu = "0.13"
cgmath = "0.18"
